image: archlinux
packages:
  - clang
  - meson
  - libuv
sources:
  - https://git.sr.ht/~kragniz/mushroom
tasks:
  - setup: |
      cd mushroom
      meson -Db_sanitize=address build
  - build: |
      cd mushroom
      ninja -C build
  - test: |
      cd mushroom
      ninja -C build test
  - check: |
      cd mushroom
      ninja -C build check
