#!/usr/bin/env python3

import sys
from subprocess import Popen

def mushroom_cmd(mushroom, mode=None, gossip_port=None, gossip_address=None,
        initial_node_port=None, initial_node_address=None, api_address=None,
        api_port=None):
    cmd = [mushroom]

    if gossip_port is not None:
        cmd.append(f'--gossip-port={gossip_port}')
    if gossip_address is not None:
        cmd.append(f'--gossip-address={gossip_address}')
    if initial_node_port is not None:
        cmd.append(f'--initial-node-port={initial_node_port}')
    if initial_node_address is not None:
        cmd.append(f'--initial-node-address={initial_node_address}')
    if api_port is not None:
        cmd.append(f'--api-port={api_port}')
    if api_address is not None:
        cmd.append(f'--api-address={api_address}')

    if mode is not None:
        cmd.append(mode)
    return cmd

def generate_cmds(mushroom, size):
    initial_node_port = 7000
    api_port = 8000
    cmds = [mushroom_cmd(mushroom, mode='spore', gossip_port=initial_node_port,
                         api_address='127.0.0.1', api_port=api_port)]

    for i in range(1, size):
        cmds.append(mushroom_cmd(mushroom,
            gossip_port=initial_node_port+i,
            initial_node_port=initial_node_port,
            initial_node_address='127.0.0.1',
            api_address='127.0.0.1',
            api_port=api_port+i))

    return cmds

def main(mushroom, size):
    commands = generate_cmds(mushroom, size)
    print('going to run a cluster with:')
    for c in commands:
        print(' '.join(c))

    procs = [Popen(i) for i in commands]
    for p in procs:
        p.wait()

if __name__ == '__main__':
    mushroom = sys.argv[1]

    if len(sys.argv) > 2:
        size = int(sys.argv[2])
    else:
        size = 3

    main(mushroom, size)
